[build]
  base = "build" # Set to the directory containing your app's build output
  publish = "build" # Set to the directory containing your app's build output
  command = "npm start" # The command to start your app
